routes/web.php
<?php
// use Counter;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', ['middleware' => 'guest', function()
{
	Counter::showAndCount('home');
     return view('frontend.landing');
}]);



Route::resource('/thread','User\ThreadController');
Route::post('/delete/thread/{id}','User\ThreadController@deleteThread');
Route::resource('comment','User\CommentController',['only'=>['update','destroy']]);
Route::post('comment/create/{thread}','User\CommentController@addThreadComment')->name('threadcomment.store');
Route::post('reply/create/{comment}','User\CommentController@addReplyComment')->name('replycomment.store');
Route::post('thread/mark-as-solution','User\ThreadController@markAsSolution')->name('markAsSolution');
Route::post('comment/like','User\LikeController@toggleLike')->name('toggleLike');

Route::get('thread/sortbycategory/{id}','User\ThreadController@ThreadSortCategory')->name('threadsort.category');
Route::get('thread/sortbyfaculty/{id}','User\ThreadController@ThreadSortFaculty')->name('threadsort.faculty');
Route::get('thread/getthreadfaculty/{id}','User\ThreadController@FacultySelect');
Route::post('thread/search','User\ThreadController@searchThreads')->name('search.threads');



Route::prefix('admin')->group(function(){

Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/login','Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/','Admin\AdminController@index')->name('admin.dashboard');



Route::prefix('category')->group(function(){

Route::get('/','Admin\CategoryController@index')->name('cat.index');
Route::post('/','Admin\CategoryController@store')->name('cat.store');
Route::post('/delete','Admin\CategoryController@destroy')->name('cat.destroy');
Route::post('/edit','Admin\CategoryController@update')->name('cat.update');
});
Route::prefix('faculty')->group(function(){

Route::get('/','Admin\FacultyController@index')->name('faculty.index');
Route::post('/','Admin\FacultyController@store')->name('faculty.store');
Route::post('/delete','Admin\FacultyController@destroy')->name('faculty.destroy');
Route::post('/update','Admin\FacultyController@update')->name('faculty.update');
Route::get('/search','Admin\FacultyController@search');

});

Route::prefix('subject')->group(function(){

Route::get('/','Admin\SubjectController@index')->name('subject.index');
Route::post('/','Admin\SubjectController@store')->name('subject.store');
Route::post('/delete','Admin\SubjectController@destroy')->name('subject.destroy');
Route::post('/update','Admin\SubjectController@update')->name('subject.update');
Route::get('/search','Admin\SubjectController@search');
});


Route::prefix('contribution')->group(function(){

Route::get('/','Admin\ContributionController@index');
Route::get('/{id}/view','Admin\ContributionController@view');
Route::post('/{id}/delete','Admin\ContributionController@delete');
});

Route::resource('post','Admin\PostController');

Route::get('events','Admin\EventController@index')->name('events.index');
Route::post('events','Admin\EventController@store')->name('events.store');
Route::post('events/delete','Admin\EventController@delete')->name('events.delete');
Route::post('events/edit','Admin\EventController@edit')->name('events.edit');

Route::post('qb/delete','Admin\QBController@destroy')->name('qb.delete');
Route::resource('qb','Admin\QBController');
// Route::post('qb/delete/{id}','Admin\QBController@destroy')->name;

Route::post('syllabus/delete','Admin\SyllabusController@destroy')->name('syllabus.delete');
Route::resource('syllabus','Admin\SyllabusController');

Route::get('opportunities','Admin\OpportunityController@index')->name('opportunities.index');
Route::post('opportunities','Admin\OpportunityController@store')->name('opportunities.store');
Route::post('opportunities/edit','Admin\OpportunityController@edit')->name('opportunities.edit');
Route::post('opportunities/delete','Admin\OpportunityController@delete')->name('opportunities.delete');

Route::get('/notes','Admin\NoteController@index')->name('notes.index');
Route::post('/notes','Admin\NoteController@store')->name('notes.store');
Route::post('/notes/update','Admin\NoteController@update')->name('notes.update');
Route::post('/notes/delete','Admin\NoteController@deleteNote')->name('notes.delete');
Route::get('/notes/filter','Admin\NoteController@filter')->name('notes.filter');
Route::get('notesfaculty/getsub','Admin\NoteController@GetSubject');
Route::get('notesfaculty/{id}','Admin\NoteController@GetFaculty');
Route::get('/sliderimage','Admin\ImageController@index')->name('sliderimage.index');
Route::post('/sliderimage','Admin\ImageController@insertslider')->name('insert.sliderimage');
Route::post('/sliderimage/delete','Admin\ImageController@delete')->name('sliderimage.delete');

});




Auth::routes();

Route::get('/home', 'Frontend\HomePageController@index')->name('home');

Route::post('/user/groups/create','User\ProfileController@create_group')->name('groups.create');
Route::post('user/group/{id}/addMembers','User\GroupController@addMembers')->name('groups.addMembers');
Route::post('user/group/{id}/removeMember','User\GroupController@removeMember')->name('groups.removeMember');
Route::get('/user/group/{id}/search','User\GroupController@searchUser');
Route::post('user/group/{id}/post','User\GroupController@message')->name('group.chat');
Route::get('/user/group/{id}','User\GroupController@group')->name('groups.group');

Route::get('admin/getfaculty/','Admin\SubjectController@CatSelect');


Route::get('/dir','DirController@index');
Route::post('/dir/root','DirController@root');
Route::post('/dir/gettree','DirController@getDirTree');
Route::post('/dir/open','DirController@openDir');
Route::post('/dir/addfolder','DirController@addFolder');
Route::post('/dir/movefolder','DirController@moveFolder');
Route::post('/dir/renamefolder','DirController@renameFolder');
Route::post('/dir/deletefolder','DirController@deleteFolder');
Route::post('/dir/deletefile','DirController@deleteFile');
Route::post('/dir/extractfile','DirController@extractFile');
Route::post('/dir/uploadfile','DirController@uploadFile');
Route::get('/dir/downloadfolder','DirController@downloadFolder');
Route::get('/dir/downloadfile','DirController@downloadFile');

Route::post('/dir/foroot','FollowDirController@root');
Route::get('/dir/downloadfofolder','FollowDirController@downloadFolder');
Route::post('/dir/foopen','FollowDirController@openDir');
Route::post('/dir/fogettree','FollowDirController@getDirTree');

Route::post('/dir/asroot','AssignmentController@root');
Route::post('/dir/asopen','AssignmentController@openDir');
Route::post('/dir/asgettree','AssignmentController@getDirTree');
Route::post('/dir/addassignment','AssignmentController@createAssignment');
Route::get('/dir/downloadasfolder','AssignmentController@downloadFolder');
Route::post('/dir/deleteasfolder','AssignmentController@deleteFolder');

Route::get('/profile/viewnotes','FollowDirController@index');

//note routes
Route::get('/note','Frontend\NoteController@notes')->name('frontend.notes');
Route::get('/getfaculty','Frontend\NoteController@getfaculty');
Route::get('/getsubject','Frontend\NoteController@getsubject');
Route::get('/note/view','Frontend\NoteController@notesview')->name('view.notes');
Route::get('note/view/{id}','Frontend\NoteController@SingleNoteView')->name('view.single');
Route::get('/note/ratenote','Frontend\NoteController@postRating')->name('rate.post');

Route::post('note/search','Frontend\SearchController@searchNotes')->name('search.notes');


Route::get('/profile','Frontend\ProfileController@profile')->name('user.profile');
Route::post('/profile/edit','Frontend\ProfileController@EditProfile')->name('edit.profile');

//facebook
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

//questionbank frontend
Route::get('/question','Frontend\QuestionBankController@questionbank')->name('question.banks');
Route::get('/question/view','Frontend\QuestionBankController@questionview');
Route::get('/getfacquestions','Frontend\QuestionBankController@getFacultyAndQuestions');
Route::get('/getquestions','Frontend\QuestionBankController@getquestions');

//frontend posts
Route::get('/blog','Frontend\PostsController@index')->name('frontendposts.index');
Route::get('/blog/{id}','Frontend\PostsController@single')->name('frontendpost.single');

Route::get('/events','Frontend\EventsController@index')->name('frontendevents.index');
Route::get('/events/{id}','Frontend\EventsController@single')->name('frontendevents.single');

Route::get('/opportunities','Frontend\OpportunitiesController@index')->name('frontendopportunities.index');
Route::get('/opportunities/{id}','Frontend\OpportunitiesController@single')->name('frontendopportunities.single');


Route::get('/getusers/directory','Frontend\SearchController@searchUserForDirectory')->name('search.users.directory');

Route::get('/directory/search','Frontend\SearchController@SearchForDirectory')->name('directory.follow');

Route::post('/directory/search','Frontend\SearchController@SearchUserDirectory')->name('searchforusers.directory');

Route::get('users/directory/{id}','Frontend\SearchController@DirectoryView')->name('getusers.directory');
Route::post('followdrive','Frontend\SearchController@DirectoryFollow')->name('drive.follow');

Route::get('contribute','Frontend\HomePageController@contribute');

app/Http/Controllers/Frontend/DirectoryController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DirectoryController extends Controller
{
    public function ViewDrive(Request $request)
    {

    }
}

app/Http/Controllers/Frontend/EventsController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Event;
use Counter;
class EventsController extends Controller
{
    public function index()
    {
        Counter::showAndCount('events');
    	$events=Event::all();
    	return view('frontend.events.index')->with('events',$events);
    }

    public function single($id)
    {
        Counter::showAndCount('events');
        Counter::showAndCount('events',$id);
        $events=Event::where('id','=',$id)->get();
   	
        return view('frontend.events.singleevents')->with('events',$events);
   }
}

app/Http/Controllers/Frontend/HomePageController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Sliderimage;
use App\Event;
use App\Post;
use App\Opportunitie;
use Counter;

class HomePageController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        Counter::showAndCount('home');
        $opportunities = Opportunitie::orderBy('id','desc')->paginate(5);     
    	$events = Event::orderBy('id','desc')->paginate(5);
    	$posts = Post::orderBy('id','desc')->paginate(5);
    	$slider = Sliderimage::all();
    	return view ('frontend.home.home')->with('slider',$slider)->with('events',$events)->with('posts',$posts)->with('opportunities',$opportunities);

    }

    public function contribute()
    {
        return view('frontend.contribute');
    }
  
}

app/Http/Controllers/Frontend/NoteController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Note;
use App\Faculty;
use App\Category;
use App\Subject;
use App\Rating;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Response;
use App\Syllabus;
use Counter;

class NoteController extends Controller
{
	public function __construct()
    {
        $this->middleware('auth');
    }
     public function notes()
    {
        Counter::showAndCount('notes');
        $faculties = Faculty::all();
        $categories = Category::all();
    	return view ('frontend.notes.note')->with('faculties',$faculties)->with('categories',$categories);
    }

    public function getfaculty()
    {

    	$cat_id = Input::get('cat_id');
        $faculties=Faculty::where('category_id','=',$cat_id)->get();
        $first=$faculties->first()->faculty_id;
        $subjects=Subject::where('faculty_id','=',$first)->get();
        return response()->json([
            'faculties'=>$faculties,
            'subjects'=>$subjects
        ]);
        
    }
    public function getsubject(Request $request)
    {
        $faculty_id = Input::get('faculty_id');
        $sub=Subject::where('faculty_id','=',$faculty_id)->get();
        return response()->json([
            'sub'=>$sub
        ]);
    }

    public function notesview(Request $request)
    {
        Counter::showAndCount('notes');
        $faculty=$request->faculty;
        $semester=$request->semester;
        $syllabus=Syllabus::where('faculty_id','=',$faculty)->where('semester','=',$semester)->get();
        $sub=$request->id;
        $sname=Subject::where('subject_id','=',$sub)->get();
        $notes=Note::where('subject_id','=',$sub)->get();        

        return view ('frontend.notes.view')->with('notes',$notes)->with('sname',$sname)->with('syllabus',$syllabus);  
    }

    public function SingleNoteView($id)
    {
        Counter::showAndCount('notes');
        $notes=Note::where('id','=',$id)->get();
         if(Rating::where('note_id',$id)->where( 'id', Auth::User()->id)->exists())
            $rated=true;
        else
            $rated = false;
    
        return view('frontend.notes.singlenote')->with('notes',$notes)->withRated($rated);

    }
    
    public function postRating(Request $request)
    {
        
        Note::where('id',$request->note_id)->increment('ratenumber',$request->rate);
        Note::where('id',$request->note_id)->increment('total_raters');

        $rating = new Rating;
        $rating->note_id=$request->note_id;
        $rating->id=$request->user_id;
        $rating->save();
        return "Success";
    }


}

app/Http/Controllers/Frontend/OpportunitiesController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Opportunitie;
use Counter;
class OpportunitiesController extends Controller
{
    public function index()
    {
        Counter::showAndCount('opportunities');
    	$oppo=Opportunitie::all();
    	return view('frontend.opportunities.index')->with('oppo',$oppo);
    }

    public function single($id)
    {
    Counter::showAndCount('opportunities');
    Counter::showAndCount('opportunities',$id);
    $oppo=Opportunitie::where('id','=',$id)->get();
   	return view('frontend.opportunities.single')->with('oppo',$oppo);
   }
}

app/Http/Controllers/Frontend/PostsController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Post;
use Counter;
class PostsController extends Controller
{
    public function index()
    {
        Counter::showAndCount('posts');
        
    	$posts=Post::all();
    	return view('frontend.posts.post')->with('posts',$posts);
    }

    public function single($id)
    {

    	Counter::showAndCount('posts');
        Counter::showAndCount('posts',$id);
        $posts=Post::where('id','=',$id)->get();
    	return view('frontend.posts.singlepost')->with('posts',$posts);
    }
}

app/Http/Controllers/Frontend/QuestionBankController.php
<?php

namespace App\Http\Controllers\Frontend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Questionbank;
use App\Faculty;
use App\Category;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Response;
use Counter;

class QuestionBankController extends Controller
{
   
    public function questionbank()
    {
        Counter::showAndCount('qb');

    	$qb=Questionbank::all();
    	$faculties = Faculty::all();
        $categories = Category::all();
    	return view ('frontend.questionbank.questionbank')->with('qb',$qb)->with('faculties',$faculties)->with('categories',$categories);
    }
    public function getFacultyAndQuestions(Request $request)
    {
        $cat_id = Input::get('cat_id');
        $faculties=Faculty::where('category_id','=',$cat_id)->get();
        $first=$faculties->first()->faculty_id;
        $questions=Questionbank::where('faculty_id','=',$first)->get();
        return response()->json([
            'faculties'=>$faculties,
            'facquestions'=>$questions
        ]);
        
    }

    public function getquestions(Request $request)
    {
        $faculty_id = Input::get('faculty_id');
        $questions=Questionbank::where('faculty_id','=',$faculty_id)->get();
        return response()->json([
            'questions'=>$questions
        ]);
    }


}

resources/views/frontend/partials/footer.blade.php
<footer>
<style type="text/css">
    
    footer {
    padding: 0px 0 0 0; 
    color: #f8f8f8;
}

footer{
    box-shadow:0px 3px 20px 0px rgb(129, 129, 129), inset 0px -1px 0px 0px #6d6d6d
}
</style>
    <div id="sub-footer">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <div class="copyright">
                        <p>&copy; Incube </p>
                        <div class="credits">
                            <!-- 
                                All the links in the footer should remain intact. 
                                You can delete the links only if you purchased the pro version.
                                Licensing information: https://bootstrapmade.com/license/
                                Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=EZnotes
                            -->
                           <!--  <a href="https://bootstrapmade.com/">Free Bootstrap Themes</a> by <a href="https://bootstrapmade.com/">BootstrapMade</a> -->
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <ul class="social-network">
                        <li><a href="#" data-placement="top" title="Facebook"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#" data-placement="top" title="Twitter"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#" data-placement="top" title="Linkedin"><i class="fa fa-linkedin"></i></a></li>
                        <li><a href="#" data-placement="top" title="Pinterest"><i class="fa fa-pinterest"></i></a></li>
                        <li><a href="#" data-placement="top" title="Google plus"><i class="fa fa-google-plus"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    </footer>
<a href="#" class="scrollup"><i class="fa fa-angle-up active"></i></a>

resources/views/frontend/partials/header.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>EZnotes</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta name="description" content="" />
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<meta name="author" content="http://bootstraptaste.com" />
<!-- css -->
<link href="{{asset('newfrontend/css/bootstrap.min.css')}}" rel="stylesheet" />
<link href="{{asset('newfrontend/css/fancybox/jquery.fancybox.css')}}" rel="stylesheet">
<link href="{{asset('newfrontend/css/jcarousel.css')}}" rel="stylesheet" />
<link href="{{asset('newfrontend/css/flexslider.css')}}" rel="stylesheet" />
<link href="{{asset('newfrontend/css/style.css')}}" rel="stylesheet" />

<!-- Theme skin -->
<link href="{{asset('newfrontend/skins/default.css')}}" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Cairo" rel="stylesheet">
  <link href="{{asset('/assets/css/sweetalert2.css')}}" rel="stylesheet" />

<script src="{{asset('/assets/js/sweetalert2.min.js')}}"></script>


<script src="{{asset('/assets/ckeditor/ckeditor.js')}}"></script>

<style type="text/css">
	h1,h3,h3,h4,post-heading{
	font-weight: 400;

	
}

h1,h2,h3,h4,h5,h6,a,span,dt,dd,p,.panel-heading{
	font-family: 'Cairo', sans-serif;
}

article .post-heading h3 a {
    font-weight: 500;
    color: #353535;
}

.widget h4, .widget h5 {
    font-weight: 500;
    margin-bottom: 20px;
}
</style>
 
<style type="text/css">
  #load{
    width:100%;
    height:100%;
    position:fixed;
    z-index:9999;
    background:url("{{asset('img/pageloading.gif')}}") no-repeat center center rgba(0,0,0,0.6)
}
	
</style>


</head>

resources/views/frontend/partials/navbar.blade.php
<div id="load"></div>
<body>
 
<div id="wrapper">

  <style type="text/css">
    ul, menu, dir {
    display: block;
    list-style-type: disc;
  
}
  </style>
   


    <header>
        <div class="navbar navbar-default navbar-static-top" >
            <div class="container" style="height: 20px">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="index.html"><span>EZ</span>notes</a>
                    
                </div>
                <div class="navbar-collapse collapse ">
                    <ul class="nav navbar-nav">

                        <li class="">


                        <a href="{{route('home')}}"> Home</a></li>


                          
                                <li><a href="{{route('frontend.notes')}}">Notes</a></li>

                               <li><a href="{{route('question.banks')}}" > Questions</a></li>
               
                          
                        </li>
                        <li><a href="{{route('frontendposts.index')}}" > Blog</a></li>
                        <li><a href="{{route('thread.index')}}" >Forum</a></li>
                        <li><a href="{{URL::to('contribute')}}" >Contribute</a></li>
                        <li><a href="contact.html">About</a></li>

                     
                        @if(Auth::User())
                        <li class="dropdown">
                             <a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false"><img src="{{asset('profile-images'.'/'.Auth::User()->picture)}}" height="30" width="30" style="border-radius: 50px;" style="color: #ddd; ">{{Auth::User()->name}} <i class="fa fa-caret-down" aria-hidden="true"></i> <b class=" icon-angle-down"></b></a>
                            <ul class="dropdown-menu">
                                 <style type="text/css">
                          a:hover {
                            color: black;
              }
                        </style>
                                <li><a href="{{route('user.profile')}}" style="color: #ddd; "><i class="fa fa-user" aria-hidden="true"></i> Profile</a></li>
                                <li> <a href="{{ route('logout') }}"

                                             onclick="event.preventDefault();
                                                      document.getElementById('logout-form').submit();" style="color: #ddd; ">
                                            <i class="fa fa-sign-out" aria-hidden="true"></i> Logout
                                         </a>

                                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                             {{ csrf_field() }}
                                         </form>
                                  </li>
               
                            </ul>
                        </li>
                        @endif
                      
                       
              
                    </ul>
                </div>
            </div>
        </div>
    </header>

resources/views/frontend/partials/scripts.blade.php
<script src="{{asset('newfrontend/js/jquery.js')}}"></script>
<script src="{{asset('newfrontend/js/jquery.easing.1.3.js')}}"></script>
<script src="{{asset('newfrontend/js/bootstrap.min.js')}}"></script>
<script src="{{asset('newfrontend/js/jquery.fancybox.pack.js')}}"></script>
<script src="{{asset('newfrontend/js/jquery.fancybox-media.js')}}"></script>
<script src="{{asset('newfrontend/js/google-code-prettify/prettify.js')}}"></script>
<script src="{{asset('newfrontend/js/portfolio/jquery.quicksand.js')}}"></script>
<script src="{{asset('newfrontend/js/portfolio/setting.js')}}"></script>
<script src="{{asset('newfrontend/js/jquery.flexslider.js')}}"></script>
<script src="{{asset('newfrontend/js/animate.js')}}"></script>
<script src="{{asset('newfrontend/js/custom.js')}}"></script>
<script type="text/javascript">
  document.onreadystatechange = function () {
    var state = document.readyState
    if (state == 'interactive') {
         document.getElementById('contents').style.visibility="hidden";
    } else if (state == 'complete') {
        setTimeout(function(){
           document.getElementById('interactive');
           document.getElementById('load').style.visibility="hidden";
           document.getElementById('contents').style.visibility="visible";
        },1000);
    }
  }
</script>



</body>
</html>