routes/web.php
<?php
// use Counter;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', ['middleware' => 'guest', function()
{
	Counter::showAndCount('home');
     return view('frontend.landing');
}]);



Route::resource('/thread','User\ThreadController');
Route::post('/delete/thread/{id}','User\ThreadController@deleteThread');
Route::resource('comment','User\CommentController',['only'=>['update','destroy']]);
Route::post('comment/create/{thread}','User\CommentController@addThreadComment')->name('threadcomment.store');
Route::post('reply/create/{comment}','User\CommentController@addReplyComment')->name('replycomment.store');
Route::post('thread/mark-as-solution','User\ThreadController@markAsSolution')->name('markAsSolution');
Route::post('comment/like','User\LikeController@toggleLike')->name('toggleLike');

Route::get('thread/sortbycategory/{id}','User\ThreadController@ThreadSortCategory')->name('threadsort.category');
Route::get('thread/sortbyfaculty/{id}','User\ThreadController@ThreadSortFaculty')->name('threadsort.faculty');
Route::get('thread/getthreadfaculty/{id}','User\ThreadController@FacultySelect');
Route::post('thread/search','User\ThreadController@searchThreads')->name('search.threads');



Route::prefix('admin')->group(function(){

Route::get('/login','Auth\AdminLoginController@showLoginForm')->name('admin.login');
Route::post('/login','Auth\AdminLoginController@login')->name('admin.login.submit');
Route::get('/','Admin\AdminController@index')->name('admin.dashboard');



Route::prefix('category')->group(function(){

Route::get('/','Admin\CategoryController@index')->name('cat.index');
Route::post('/','Admin\CategoryController@store')->name('cat.store');
Route::post('/delete','Admin\CategoryController@destroy')->name('cat.destroy');
Route::post('/edit','Admin\CategoryController@update')->name('cat.update');
});
Route::prefix('faculty')->group(function(){

Route::get('/','Admin\FacultyController@index')->name('faculty.index');
Route::post('/','Admin\FacultyController@store')->name('faculty.store');
Route::post('/delete','Admin\FacultyController@destroy')->name('faculty.destroy');
Route::post('/update','Admin\FacultyController@update')->name('faculty.update');
Route::get('/search','Admin\FacultyController@search');

});

Route::prefix('subject')->group(function(){

Route::get('/','Admin\SubjectController@index')->name('subject.index');
Route::post('/','Admin\SubjectController@store')->name('subject.store');
Route::post('/delete','Admin\SubjectController@destroy')->name('subject.destroy');
Route::post('/update','Admin\SubjectController@update')->name('subject.update');
Route::get('/search','Admin\SubjectController@search');
});


Route::prefix('contribution')->group(function(){

Route::get('/','Admin\ContributionController@index');
Route::get('/{id}/view','Admin\ContributionController@view');
Route::post('/{id}/delete','Admin\ContributionController@delete');
});

Route::resource('post','Admin\PostController');

Route::get('events','Admin\EventController@index')->name('events.index');
Route::post('events','Admin\EventController@store')->name('events.store');
Route::post('events/delete','Admin\EventController@delete')->name('events.delete');
Route::post('events/edit','Admin\EventController@edit')->name('events.edit');

Route::post('qb/delete','Admin\QBController@destroy')->name('qb.delete');
Route::resource('qb','Admin\QBController');
// Route::post('qb/delete/{id}','Admin\QBController@destroy')->name;

Route::post('syllabus/delete','Admin\SyllabusController@destroy')->name('syllabus.delete');
Route::resource('syllabus','Admin\SyllabusController');

Route::get('opportunities','Admin\OpportunityController@index')->name('opportunities.index');
Route::post('opportunities','Admin\OpportunityController@store')->name('opportunities.store');
Route::post('opportunities/edit','Admin\OpportunityController@edit')->name('opportunities.edit');
Route::post('opportunities/delete','Admin\OpportunityController@delete')->name('opportunities.delete');

Route::get('/notes','Admin\NoteController@index')->name('notes.index');
Route::post('/notes','Admin\NoteController@store')->name('notes.store');
Route::post('/notes/update','Admin\NoteController@update')->name('notes.update');
Route::post('/notes/delete','Admin\NoteController@deleteNote')->name('notes.delete');
Route::get('/notes/filter','Admin\NoteController@filter')->name('notes.filter');
Route::get('notesfaculty/getsub','Admin\NoteController@GetSubject');
Route::get('notesfaculty/{id}','Admin\NoteController@GetFaculty');
Route::get('/sliderimage','Admin\ImageController@index')->name('sliderimage.index');
Route::post('/sliderimage','Admin\ImageController@insertslider')->name('insert.sliderimage');
Route::post('/sliderimage/delete','Admin\ImageController@delete')->name('sliderimage.delete');

});




Auth::routes();

Route::get('/home', 'Frontend\HomePageController@index')->name('home');

Route::post('/user/groups/create','User\ProfileController@create_group')->name('groups.create');
Route::post('user/group/{id}/addMembers','User\GroupController@addMembers')->name('groups.addMembers');
Route::post('user/group/{id}/removeMember','User\GroupController@removeMember')->name('groups.removeMember');
Route::get('/user/group/{id}/search','User\GroupController@searchUser');
Route::post('user/group/{id}/post','User\GroupController@message')->name('group.chat');
Route::get('/user/group/{id}','User\GroupController@group')->name('groups.group');

Route::get('admin/getfaculty/','Admin\SubjectController@CatSelect');


Route::get('/dir','DirController@index');
Route::post('/dir/root','DirController@root');
Route::post('/dir/gettree','DirController@getDirTree');
Route::post('/dir/open','DirController@openDir');
Route::post('/dir/addfolder','DirController@addFolder');
Route::post('/dir/movefolder','DirController@moveFolder');
Route::post('/dir/renamefolder','DirController@renameFolder');
Route::post('/dir/deletefolder','DirController@deleteFolder');
Route::post('/dir/deletefile','DirController@deleteFile');
Route::post('/dir/extractfile','DirController@extractFile');
Route::post('/dir/uploadfile','DirController@uploadFile');
Route::get('/dir/downloadfolder','DirController@downloadFolder');
Route::get('/dir/downloadfile','DirController@downloadFile');

Route::post('/dir/foroot','FollowDirController@root');
Route::get('/dir/downloadfofolder','FollowDirController@downloadFolder');
Route::post('/dir/foopen','FollowDirController@openDir');
Route::post('/dir/fogettree','FollowDirController@getDirTree');

Route::post('/dir/asroot','AssignmentController@root');
Route::post('/dir/asopen','AssignmentController@openDir');
Route::post('/dir/asgettree','AssignmentController@getDirTree');
Route::post('/dir/addassignment','AssignmentController@createAssignment');
Route::get('/dir/downloadasfolder','AssignmentController@downloadFolder');
Route::post('/dir/deleteasfolder','AssignmentController@deleteFolder');

Route::get('/profile/viewnotes','FollowDirController@index');

//note routes
Route::get('/note','Frontend\NoteController@notes')->name('frontend.notes');
Route::get('/getfaculty','Frontend\NoteController@getfaculty');
Route::get('/getsubject','Frontend\NoteController@getsubject');
Route::get('/note/view','Frontend\NoteController@notesview')->name('view.notes');
Route::get('note/view/{id}','Frontend\NoteController@SingleNoteView')->name('view.single');
Route::get('/note/ratenote','Frontend\NoteController@postRating')->name('rate.post');

Route::post('note/search','Frontend\SearchController@searchNotes')->name('search.notes');


Route::get('/profile','Frontend\ProfileController@profile')->name('user.profile');
Route::post('/profile/edit','Frontend\ProfileController@EditProfile')->name('edit.profile');

//facebook
Route::get('login/{provider}', 'Auth\LoginController@redirectToProvider');
Route::get('login/{provider}/callback', 'Auth\LoginController@handleProviderCallback');

//questionbank frontend
Route::get('/question','Frontend\QuestionBankController@questionbank')->name('question.banks');
Route::get('/question/view','Frontend\QuestionBankController@questionview');
Route::get('/getfacquestions','Frontend\QuestionBankController@getFacultyAndQuestions');
Route::get('/getquestions','Frontend\QuestionBankController@getquestions');

//frontend posts
Route::get('/blog','Frontend\PostsController@index')->name('frontendposts.index');
Route::get('/blog/{id}','Frontend\PostsController@single')->name('frontendpost.single');

Route::get('/events','Frontend\EventsController@index')->name('frontendevents.index');
Route::get('/events/{id}','Frontend\EventsController@single')->name('frontendevents.single');

Route::get('/opportunities','Frontend\OpportunitiesController@index')->name('frontendopportunities.index');
Route::get('/opportunities/{id}','Frontend\OpportunitiesController@single')->name('frontendopportunities.single');


Route::get('/getusers/directory','Frontend\SearchController@searchUserForDirectory')->name('search.users.directory');

Route::get('/directory/search','Frontend\SearchController@SearchForDirectory')->name('directory.follow');

Route::post('/directory/search','Frontend\SearchController@SearchUserDirectory')->name('searchforusers.directory');

Route::get('users/directory/{id}','Frontend\SearchController@DirectoryView')->name('getusers.directory');
Route::post('followdrive','Frontend\SearchController@DirectoryFollow')->name('drive.follow');

Route::get('contribute','Frontend\HomePageController@contribute');

resources/views/admin/partials/footer.blade.php
        </body>

      <footer class="footer">
            <div class="container-fluid">
                <nav class="pull-left">
                    <ul>
                        <li>
                            <a href="#">
                                Home
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Company
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                Portfolio
                            </a>
                        </li>
                        <li>
                            <a href="#">
                               Blog
                            </a>
                        </li>
                    </ul>
                </nav>
                <p class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> <a href="http://www.creative-tim.com">Creative Tim</a>, made with love for a better web
                </p>
            </div>
        </footer>

    </div>
</div>


</html>

resources/views/admin/partials/header.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" href="{{asset('assets/img/favicon.png')}}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>Easy Notes</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />




    <!-- Animation library for notifications   -->
    <link href="{{asset('assets/css/animate.min.css')}}" rel="stylesheet"/>

    <!--  Light Bootstrap Table core CSS    -->
    <link href="{{asset('assets/css/light-bootstrap-dashboard.css')}}" rel="stylesheet"/>


    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="{{asset('/assets/ckeditor/ckeditor.js')}}"></script>
    <link href="{{asset('/assets/css/sweetalert2.css')}}" rel="stylesheet" />


    <!--     Fonts and icons     -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
    <link href="{{asset('assets/css/pe-icon-7-stroke.css')}}" rel="stylesheet" />
    <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">

</head>
     
<body>

resources/views/admin/partials/messages.blade.php
@if(Session::has('success'))


	
		<div class="container">
			<div class="row">

			<div class="alert alert-success" role="alert">
					
					<strong>Success:</strong>{{Session::get('success')}}
			</div>
		</div>
	</div>
	

@endif

@if(!$errors->isEmpty())

<div class="container">

	<div class="alert alert-warning" role="alert">
	<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
		<strong>Errors:</strong>
		<ul>
		@foreach($errors->all() as $error)
				
			<li>{{ $error }}</li>

		@endforeach
		</ul>
	</div>	
</div>	

@endif

resources/views/admin/partials/navbar.blade.php
<div class="main-panel">
        <nav class="navbar navbar-default navbar-fixed">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Dashboard</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="fa fa-dashboard"></i>
                                <p class="hidden-lg hidden-md">Dashboard</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="fa fa-globe"></i>
                                    <b class="caret hidden-sm hidden-xs"></b>
                                    <span class="notification hidden-sm hidden-xs">5</span>
                                    <p class="hidden-lg hidden-md">
                                        5 Notifications
                                        <b class="caret"></b>
                                    </p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>
                        <li>
                           <a href="">
                                <i class="fa fa-search"></i>
                                <p class="hidden-lg hidden-md">Search</p>
                            </a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        <li>
                           <a href="">
                               <p>Account</p>
                            </a>
                        </li>
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <p>
                                        Dropdown
                                        <b class="caret"></b>
                                    </p>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Action</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li><a href="#">Another action</a></li>
                                <li><a href="#">Something</a></li>
                                <li class="divider"></li>
                                <li><a href="#">Separated link</a></li>
                              </ul>
                        </li>
                        <li>
                                         <a href="{{ route('logout') }}"
                                             onclick="event.preventDefault();
                                                      document.getElementById('logout-form').submit();">
                                             Logout
                                         </a>

                                         <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                             {{ csrf_field() }}
                                         </form>
                                     </li>

                        <li class="separator hidden-lg hidden-md"></li>
                    </ul>
                </div>
            </div>
        </nav>

resources/views/admin/partials/scripts.blade.php
	{{-- <script src="{{asset('/assets/js/bootstrap.min.js')}}" type="text/javascript"></script> --}}

	<!--  Checkbox, Radio & Switch Plugins -->
	
{{--  --}}
	<!--  Charts Plugin -->
	

    <!--  Notifications Plugin    -->
    
    

  

 <script src="{{asset('assets/js/jquery-1.10.2.js')}}" type="text/javascript"></script>
	

	<!--  Checkbox, Radio & Switch Plugins -->
	<script src="{{asset('assets/js/bootstrap-checkbox-radio-switch.js')}}"></script>

	<!--  Charts Plugin -->
	<script src="{{asset('assets/js/chartist.min.js')}}"></script>

    <!--  Notifications Plugin    -->
    <script src="{{asset('assets/js/bootstrap-notify.js')}}"></script>

    <!--  Google Maps Plugin    -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false"></script>

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{{asset('assets/js/light-bootstrap-dashboard.js')}}"></script>



	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!--  Google Maps Plugin    -->
    

    <!-- Light Bootstrap Table Core javascript and methods for Demo purpose -->
	<script src="{{asset('/assets/js/light-bootstrap-dashboard.js')}}"></script>

	<!-- Light Bootstrap Table DEMO methods, don't include it in your project! -->
   
    <script src="{{asset('/assets/js/sweetalert2.min.js')}}"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

	

resources/views/admin/partials/sidebar.blade.php
<body>

  <div class="wrapper">
    <div class="sidebar" data-color="purple" data-image="{{asset('assets/img/sidebar-5.jpg')}}">

<!--

Tip 1: you can change the color of the sidebar using: data-color="blue | azure | green | orange | red | purple"
Tip 2: you can also add an image using data-image tag

-->

<div class="sidebar-wrapper">
  <div class="logo">
    <a href="http://www.creative-tim.com" class="simple-text">
      Creative Tim
    </a>
  </div>

  <ul class="nav">

    <li class="{{ Request::segment(2)=='' ? 'active': '' }}">
      <a href="{{route('admin.dashboard')}}">
        <i class="pe-7s-graph"></i>
        <p>Dashboard</p>
      </a>
    </li>
    <li class="{{ Request::segment(2)=='category' ? 'active': '' }}">
      <a  href="{{route("cat.index")}}">
        <i class="pe-7s-news-paper"></i>
        <p>Categories</p>
      </a>
    </li>
    <li class="{{ Request::segment(2)=='faculty' ? 'active': '' }}">
      <a href="{{route('faculty.index')}}">
        <i class="pe-7s-note2"></i>
        <p>Faculties</p>
      </a>
    </li>
    <li class="{{ Request::segment(2)=='subject' ? 'active': '' }}">
      <a  href="{{route('subject.index')}}">
        <i class="pe-7s-science"></i>
        <p>Subjects</p>
      </a>
    </li>
    <li class="{{ Request::segment(2)=='qb' ? 'active': '' }}">
      <a  href="{{URL::to('admin/qb')}}">
        <i class="fa fa-question" aria-hidden="true"></i>
        <p>Questions</p>
      </a>
    </li>
    <li class="{{ Request::segment(2)=='post' ? 'active': '' }}">
      <a  href="{{route('post.index')}}">
        <i class="fa fa-newspaper-o" aria-hidden="true"></i>
        <p>Posts</p>
      </a>
    </li>
    <li class="{{ Request::segment(2)=='notes' ? 'active': '' }}">
      <a  href="{{route('notes.index')}}">
       <i class="pe-7s-note2"></i>
        <p>Notes</p>
      </a>
    </li>

    <li class="{{ Request::segment(2)=='events' ? 'active': '' }}">
      <a  href="{{route('events.index')}}"/>
      <i class="fa fa-calendar" aria-hidden="true"></i>
      <p>Events</p>
    </a>
  </li>
    
    <li class="{{ Request::segment(2)=='opportunities' ? 'active': '' }}">
      <a  href="{{route('opportunities.index')}}"/>
      <i class="fa fa-calendar" aria-hidden="true"></i>
      <p>Opportunities</p>
    </a>
  </li>

  <li class="{{ Request::segment(2)=='sliderimage' ? 'active': '' }}">
      <a  href="{{route('sliderimage.index')}}"/>
      <i class="pe-7s-photo" aria-hidden="true"></i>
      <p>Images Manager</p>
    </a>
  </li>
  <li class="{{ Request::segment(2)=='syllabus' ? 'active': '' }}">
      <a  href="{{route('syllabus.index')}}"/>
      <i class="pe-7s-photo" aria-hidden="true"></i>
      <p>Syllabus</p>
    </a>
  </li>
   <li class="{{ Request::segment(2)=='contribution' ? 'active': '' }}">
      <a  href="{{URL::to('/admin/contribution')}}"/>
      <i class="pe-7s-photo" aria-hidden="true"></i>
      <p>Contrubutions</p>
    </a>
  </li>


</ul>

</div>
</div>